# Generated by Django 2.0.7 on 2019-04-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0002_hospital_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'ordering': ['name'], 'verbose_name_plural': 'hospitals'},
        ),
    ]
