# Generated by Django 2.0.7 on 2019-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0003_auto_20190407_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
