# Generated by Django 2.0.7 on 2019-04-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0004_hospital_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=256, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'ordering': ['date_added'],
            },
        ),
    ]
