# Generated by Django 2.0.7 on 2019-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0005_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='problem',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
