# Generated by Django 2.0.7 on 2019-04-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0006_auto_20190420_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='sex',
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneno',
            field=models.CharField(default=91, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='problem',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
