# Generated by Django 2.0.7 on 2019-04-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalcare', '0007_auto_20190420_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phoneno',
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
