# Generated by Django 2.0.7 on 2019-03-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('moblie_no', models.CharField(max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'donate',
                'ordering': ['date_added'],
            },
        ),
    ]
