# Generated by Django 2.0.7 on 2019-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
