# Generated by Django 2.0.7 on 2019-04-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_donate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='donate_id',
        ),
    ]
