# Generated by Django 2.0.7 on 2019-04-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20190418_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='total',
            new_name='amount',
        ),
    ]
