# Generated by Django 2.0.7 on 2019-04-19 07:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_auto_20190418_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='donate',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
