# Generated by Django 2.0.7 on 2019-04-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_remove_donate_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='moblie_no',
        ),
    ]
