# Generated by Django 2.0.7 on 2019-04-19 12:12

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0009_remove_donate_moblie_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
