# Generated by Django 2.0.7 on 2019-04-19 12:24

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_auto_20190419_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='phoneno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=1, max_length=128, region=None),
        ),
    ]
